name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Build dalamud
        run: |
          dotnet publish `
          --configuration Release `
          --output artifacts `
          src/Dalamud

      - uses: actions/upload-artifact@v2
        with:
          name: dalamud
          path: |
            artifacts
